// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwzrvgxqqyfhitgstdns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3enJ2Z3hxcXlmaGl0Z3N0ZG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDI3NTEsImV4cCI6MjA3Mzk3ODc1MX0.IyVGViawOdLEUuxyiAJ9J6xvmLXTnM-Do-aTzrUWyPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});